environment:
  matrix:
    - job_name: Windows
#      QTDIR: C:\Qt\5.10.1\msvc2017_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

    - job_name: OSX
      APPVEYOR_BUILD_WORKER_IMAGE: macOS

configuration:
  - Debug
  - Release
  - Retail

clone_script:
  - cmd: git clone -q --recursive --branch=master https://github.com/milostosic/rapp.git ..\rapp

install:
  - git clone --depth 1 https://github.com/milostosic/build ..\build
  - git clone --depth 1 https://github.com/milostosic/rbase ..\rbase
  - git clone --depth 1 https://github.com/bkaradzic/bx.git   ..\bx
  - git clone --depth 1 https://github.com/bkaradzic/bimg.git ..\bimg
  - git clone --depth 1 https://github.com/bkaradzic/bgfx.git ..\bgfx
  - git clone --depth 1 https://github.com/dougbinks/enkiTS ..\enkiTS

matrix:
  fast_finish: true

shallow_clone: true

for:
  
# ======================================
#      Windows
# ======================================
-
  matrix:
    only:
    - job_name: Windows

  init:
  - ..\build\tools\bin\windows\genie --file=genie\genie.lua vs2019

  build: ../.build/windows/vs2019/rapp/projects/rapp.sln
  
# ======================================
#      Linux
# ======================================
-
  matrix:
    only:
    - job_name: Linux

  init:
  - ../build/tools/bin/linux/genie --file=genie/genie.lua -gcc=linux-gcc-9

  build_script:
  - make -f ../.build/linux/linux/gcc-9/rapp/projects/rapp.make

# ======================================
#      macOS
# ======================================
-
  matrix:
    only:
    - job_name: OSX

  init:
  - ../build/tools/bin/darwin/genie --file=genie/genie.lua -gcc=osx

  build_script:
  - make -f ../.build/osx/clang/rapp/projects/rapp.make
