shallow_clone: true

os:
  - Visual Studio 2017

environment:
  matrix:
  - TOOLSET: vs2015
  - TOOLSET: vs2017

configuration:
  - Debug
  - Release
  - Retail

clone_script:
  - cmd: git clone -q --recursive --branch=master https://github.com/milostosic/rapp.git ..\rapp

install:
  - git clone --depth 1 https://github.com/milostosic/build ..\build
  - git clone --depth 1 https://github.com/milostosic/rbase ..\rbase
  - git clone --depth 1 https://github.com/bkaradzic/bx.git   ..\bx
  - git clone --depth 1 https://github.com/bkaradzic/bimg.git ..\bimg
  - git clone --depth 1 https://github.com/bkaradzic/bgfx.git ..\bgfx
  - git clone --depth 1 https://github.com/01org/tbb.git ..\tbb
  - git clone --depth 1 https://github.com/memononen/nanovg.git ..\nanovg
  - ..\build\tools\windows\genie --file=genie\genie.lua %TOOLSET%

build:
  project: ../.build/windows/$(TOOLSET)/rapp/projects/rapp.sln
